### ISSUE TITLE
remove metalnx groups database and go straight to icat

### ISSUE THREAD

**Issue by michael-conway** [DICE-UNC/jargon-irods-ext#11]
linked to https://github.com/irods-contrib/metalnx-web/issues/111 remove metalnx group and users database and go straight to icat

**Comment by michael-conway** [comment]
first order of biz..is this a db fix or can we yank groups db?

**Comment by trel** [comment]
let's let iRODS be the source of truth - and remove writing groups info down anywhere else.

in-memory caching is fine, but please nothing persistent.

**Comment by michael-conway** [comment]
changes flow into https://github.com/irods-contrib/metalnx-web/issues/111

**Comment by michael-conway** [comment]
NB migration changes for database not yet done, will be last item
