### ISSUE TITLE
Groupadmin functions and user admin functions, redesign and remove user from db

### ISSUE THREAD

**Issue by michael-conway** [DICE-UNC/jargon-irods-ext#15]
Allow groupadmin to do actions thru interface. Refactoring of user and group functions to Vue.js (this will be in steps). Remove user and user bookmarks from database and shut down synch processes.

**Comment by michael-conway** [comment]
Groupadmin can now view user/group pages but general redesign and removal of datagriduser from metalnx database are pre-reqs to get this all done. My feeling is that we table the completion of the groupadmin functions until we get to the release supporting the ability to add vue.js subpages and use that to rework user and group management.

**Comment by trel** [comment]
seems good
