### ISSUE TITLE
mapListingEntryToDataGridCollectionAndDataObject() does not capture the size of data objects

### ISSUE THREAD

**Issue by korydraughn** [DICE-UNC/jargon-irods-ext#27]
https://github.com/DICE-UNC/jargon-irods-ext/blob/5819dbc44f38757baa331ec44f68ec174167588f/emc-metalnx-services/src/main/java/com/emc/metalnx/services/irods/CollectionServiceImpl.java#L867

**Comment by trel** [comment]
@michael-conway  kory's already got a PR ready
