### ISSUE TITLE
AdminServicesImpl uses the jobs configuration settings to get admin account

### ISSUE THREAD

**Issue by JustinKyleJames** [DICE-UNC/jargon-irods-ext#43]
The `AdminServicesImpl` uses the jobs configuration settings to get admin account user and password.

https://github.com/DICE-UNC/jargon-irods-ext/blob/b65d3d764b71182b0db5a376331723ccb5b7e763/emc-metalnx-services/src/main/java/com/emc/metalnx/services/irods/AdminServicesImpl.java#L105-L106)

The `ConfigServiceImpl` class does not even provide a setting to get `irods.admin.user` and `irods.admin.password`.  As far as I can tell these settings are not even being used by Metalnx.

Since the jobs are going away with the removal of the database, change the ConfigService classes to not refer to jobs but instead refer to the `irods.admin.*` and change `AdminServiceImpl` to use these new methods.

Note:  The need for the admin account may be going away soon but for now make this change.

**Comment by trel** [comment]
Correct - we don't need any account information in the pure client configuration anymore.

The logged-in user is what should be used to authenticate for every API call.  Now we get to decide where the credential/token is stored for the duration of a 'session'.

**Comment by JustinKyleJames** [comment]
> Correct - we don't need any account information in the pure client configuration anymore.
> 
> The logged-in user is what should be used to authenticate for every API call. Now we get to decide where the credential/token is stored for the duration of a 'session'.

Yes, but that is not in the scope of this issue.  This issue is addresses what is called from `AdminServiceImplementation.authenticateIRODSAccount()` so the context is that it is the admin configuration.  This method/class will likely not be called from Metalnx once we remove the requirement for an admin account.

**Comment by trel** [comment]
certainly agree it's a different issue.   clean this one up - and then separately, we can remove all the admin credentials.

**Comment by alanking** [comment]
@JustinKyleJames - Please close if complete. Thanks.

@trel / @korydraughn - Not sure how we do releases in this repo, but looks like 4.3.5.0 might be the next one unless something is going to change. Maybe we should consider using milestones to make tracking that a bit easier?

**Comment by korydraughn** [comment]
Yes, 4.3.5.0 will be the next release.

We can see how milestones feel. Please open one for this repo.

**Comment by JustinKyleJames** [comment]
This work has been merged.  Closing this issue.
